### ISSUE TITLE
The error ocurred when I run dcnv3/tests/test_dcnv3_module.py and test_grad.py

### ISSUE THREAD

**Issue by leij0318** [inspiros/dcnv3#1]
The error occurred when I run dcnv3/tests/test_dcnv3_module.py
#####################################################
DCNv3(
  (dw_conv): Sequential(
    (0): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=4)
    (1): Sequential(
      (0): to_channels_last()
      (1): LayerNorm((4,), eps=1e-06, elementwise_affine=True)
    )
    (2): GELU(approximate='none')
  )
  (offset): Linear(in_features=4, out_features=36, bias=True)
  (mask): Linear(in_features=4, out_features=18, bias=True)
  (input_proj): Linear(in_features=4, out_features=4, bias=True)
  (output_proj): Linear(in_features=4, out_features=4, bias=True)
)
Traceback (most recent call last):
  File "D:\project(yolo)\dcnv3\tests\test_dcnv3_module.py", line 17, in <module>
    test_dcnv3_module()
  File "D:\project(yolo)\dcnv3\tests\test_dcnv3_module.py", line 12, in test_dcnv3_module
    output = m(x)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\dcnv3\ops\_dcnv3.py", line 214, in forward
    x = self.output_proj(x)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anaconda3\envs\yolo\Lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not NoneType
############################################################
Input is NoneType? Why?

The error ocurred when I run dcnv3/tests/test_grad.py
###############################################################
Traceback (most recent call last):
  File "D:\project(yolo)\dcnv3\tests\test_grad.py", line 61, in <module>
    test_dcnv3()
  File "D:\project(yolo)\dcnv3\tests\test_grad.py", line 40, in test_dcnv3
    c_output.sum().backward()
AttributeError: 'NoneType' object has no attribute 'sum'
#####################################################
Original code below:

    c_output = dcnv3.ops.dcnv3(input, offset, mask,
                               kernel_h, kernel_w,
                               stride_h, stride_w,
                               pad_h, pad_w,
                               dilation_h, dilation_w,
                               group, group_channels,
                               offset_scale,
                               im2col_step,
                               remove_center)
    c_output.sum().backward()

c_output is Nonetype? Why?

**Comment by inspiros** [comment]
Sorry, I forgot this repo is mine and almost ignored GitHub's notification 😂.

Honestly, I don't know what could possibly go wrong as it still works on my machine. Did you install the **TestPyPI** wheel or compile from source? Note that the **TestPyPI** wheel only works if your configuration matches that of the GitHub Action server where I built them. Even if you installed from source, there are a lot of possibilities.

I just updated the **TestPyPI** wheel to make it compatible with `torch>=2.1.0` and **Cuda 12.1** (previously it could run on `1.9.0<=torch<=2.0.1` and **Cuda 11.8**). When you run the script again if you see this error, then you need to recompile from source:
```
Detected that PyTorch and Extension were compiled with different CUDA versions. PyTorch has CUDA Version={t_major}.{t_minor} and Extension has CUDA Version={ext_major}.{ext_minor}. Please reinstall the Extension that matches your PyTorch install.
```
